version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github_actions"
    commit-message:
      prefix: "github-actions"
    open-pull-requests-limit: 30

  - package-ecosystem: "docker"
    directory: ".devcontainer"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Asia/Tokyo"
      day: 'saturday'
    open-pull-requests-limit: 10
    target-branch: "main"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
    assignees:
      - "Tsuyoshi84"