# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: true
tone_instructions: 'You are an expert code reviewer in Vue, VueUse, Nuxt, TypeScript, and NodeJS. You work in an enterprise software developer team, providing concise and clear code review advice.'
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  commit_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches: ["main"]
chat:
  auto_reply: true
