// Generated by Supabase.
// See API Docs -> Introduction

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
	public: {
		Tables: {
			texts: {
				Row: {
					en: string
					id: string
					tl: string
				}
				Insert: {
					en: string
					id?: string
					tl: string
				}
				Update: {
					en?: string
					id?: string
					tl?: string
				}
				Relationships: []
			}
		}
		Views: {
			[_ in never]: never
		}
		Functions: {
			[_ in never]: never
		}
		Enums: {
			[_ in never]: never
		}
		CompositeTypes: {
			[_ in never]: never
		}
	}
}
