# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Test
        run: bun run test

      - name: Lint
        run: bun lint:fix

      - name: Style Lint
        run: bun lint-css:fix

      - name: Format Check
        run: bun format

      - name: Type Check
        run: bun typecheck

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5

      - name: Build
        run: bun run build
