name: Update Nuxt Dependencies

on:
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Update Nuxt dependencies
        run: |
          npx nuxt@latest upgrade --force
          
      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: update nuxt dependencies'
          title: 'chore: Update Nuxt dependencies ${{ format(github.event.repository.updated_at, ''yyyy-MM-dd HH:mm'') }}'
          body: |
            Automated PR to update Nuxt dependencies using `npx nuxt@latest upgrade --force`
            
            This PR was created automatically by the Update Nuxt Dependencies workflow.
          branch: chore/update-nuxt-deps-${{ format(github.event.repository.updated_at, 'yyyy-MM-dd-HH-mm') }}
          delete-branch: true
          base: main