name: Update Dependencies

on:
  workflow_dispatch:
  schedule:
    # Run at 23:00 UTC on Friday (8:00 AM Saturday JST)
    - cron: '0 23 * * 5'

jobs:
  update-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --no-save

      - name: Update dependencies
        run: |
          bun update --latest
          
      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_FOR_ACTIONS }}
          commit-message: 'chore: update dependencies'
          title: 'chore: Update dependencies'
          body: |
            Automated PR to update dependencies using `bun update --latest`
            
            This PR was created automatically by the Update Dependencies workflow.
          branch: chore/update-deps-${{ github.run_number }}
          delete-branch: true
          base: main