name: Update Nuxt Dependencies

on:
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --no-save

      - name: Update Nuxt dependencies
        run: |
          bunx nuxi@latest upgrade --dedupe
          
      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_FOR_ACTIONS }}
          commit-message: 'chore: update nuxt dependencies'
          title: 'chore: Update Nuxt dependencies'
          body: |
            Automated PR to update Nuxt dependencies using `bunx nuxt@latest upgrade --force`
            
            This PR was created automatically by the Update Nuxt Dependencies workflow.
          branch: chore/update-nuxt-deps-${{ github.run_number }}
          delete-branch: true
          base: main